[platformio]
default_envs = heltec_wifi_lora_32_V2_sim

[env]
platform = espressif32
board = heltec_wifi_lora_32_V2
framework = arduino
monitor_speed = 115200

# Board-specific configuration
board_build.f_cpu = 240000000L

# External libraries (Arduino core already includes WiFi + HTTPClient)
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    sandeepmistry/LoRa @ ^0.8.0
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.17

# Build flags
build_flags = 
    -D CORE_DEBUG_LEVEL=1

# Upload settings
upload_speed = 921600

[env:heltec_wifi_lora_32_V2_sim]
build_src_filter = +<main_simulator.cpp>

[env:heltec_wifi_lora_32_V2_hw]
build_src_filter = +<main.cpp>
